# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Away at Edinburgh
email: henriqueferrolho@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is a blog about my stay at Edinburgh.
baseurl: "/away-at-edinburgh" # the subpath of your site, e.g. /blog
url: "http://ferrolho.github.io" # the base hostname & protocol for your site
github_username:    ferrolho
instagram_username: henriqueferrolho
#twitter_username:   hferrolho

# Build settings
markdown: kramdown
